//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperOnline_ASP_NET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Contenido_Listas
    {
        [Key]
        public int contenido_listas_id { get; set; }
        public int lista_id { get; set; }
        public string tipo { get; set; }

        ////[Required]
        //[StringLength(20)]
        //[DisplayName("Nombre de la lista")]
        public virtual Lista Lista { get; set; }
        
        ////[Required]
        //[DisplayName("Item")]
        public virtual Tipos Tipos { get; set; }
    }
}
