//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperOnline_ASP_NET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_pedido
    {
        public int detalle_pedido_id { get; set; }
        public int producto_id { get; set; }
        public int cantidad_producto { get; set; }
        public decimal precio { get; set; }
        public decimal sub_total { get; set; }
        public int pedido_id { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
