//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperOnline_ASP_NET_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuperOnlineEntities : DbContext
    {
        public SuperOnlineEntities()
            : base("name=SuperOnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categoria> Categorias { get; set; }
        public DbSet<Comentario> Comentarios { get; set; }
        public DbSet<Contenido_Listas> Contenido_Listas { get; set; }
        public DbSet<Detalle_pedido> Detalle_pedido { get; set; }
        public DbSet<Gondola> Gondolas { get; set; }
        public DbSet<Lista> Listas { get; set; }
        public DbSet<Pedido> Pedidos { get; set; }
        public DbSet<Producto> Productos { get; set; }
        public DbSet<Super_mercados> Super_mercados { get; set; }
        public DbSet<Tipos> Tipos { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
    }
}
