//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperOnline_ASP_NET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.Detalle_pedido = new HashSet<Detalle_pedido>();
        }
        [Key]
        [DisplayName("Pedido")]
        public int pedido_id { get; set; }

        [Required]
        [StringLength(15)]
        [DisplayName("Estado")]
        public string estado { get; set; }

        [Required]
        [DisplayName("Total")]
        public decimal total_precio { get; set; }

        [Required]
        public System.DateTime fecha { get; set; }
        [Required]
        public int usuario_id { get; set; }
        [Required]
        [DisplayName("Super Mercado")]
        public string super_mercado { get; set; }
    
        public virtual ICollection<Detalle_pedido> Detalle_pedido { get; set; }
        public virtual Super_mercados Super_mercados { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
