//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperOnline_ASP_NET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Super_mercados
    {
        public Super_mercados()
        {
            this.Pedidos = new HashSet<Pedido>();
            this.Productos = new HashSet<Producto>();
        }
    
        public string nombre { get; set; }
    
        public virtual ICollection<Pedido> Pedidos { get; set; }
        public virtual ICollection<Producto> Productos { get; set; }
    }
}
