//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperOnline_ASP_NET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipos
    {
        public Tipos()
        {
            this.Contenido_Listas = new HashSet<Contenido_Listas>();
            this.Productos = new HashSet<Producto>();
        }
    
        public string nombre { get; set; }
        public string categoria { get; set; }
    
        public virtual Categoria Categoria1 { get; set; }
        public virtual ICollection<Contenido_Listas> Contenido_Listas { get; set; }
        public virtual ICollection<Producto> Productos { get; set; }
    }
}
