//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperOnline_ASP_NET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Comentarios = new HashSet<Comentario>();
            this.Listas = new HashSet<Lista>();
            this.Pedidos = new HashSet<Pedido>();
        }
        

        public int usuario_id { get; set; }

        [Required(ErrorMessage = "Cédula es requerida")]
        [StringLength(20, ErrorMessage = "Cédula debe tener menos de 30 caracteres")]
        [DisplayName("Cédula")]
        public string cedula { get; set; }

        [Required(ErrorMessage = "Correo Electrónico es requerido")]
        [StringLength(30, ErrorMessage = "Corero Electrónico debe tener menos de 30 caracteres")]
        [DisplayName("Correo Electrónico")]
        public string correo { get; set; }

        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage="Apellido no debe contener números")]
        [Required(ErrorMessage = "Apellido es requerido")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "Apellido debe contener entre 2 a 30 caracteres")]
        [DisplayName("Apellido")]
        public string apellido { get; set; }

        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Nombre no debe contener números")]
        [Required(ErrorMessage = "Nombre es requerido")]
        [StringLength(20, MinimumLength=2, ErrorMessage="Nombre debe contener entre 2 a 20 caracteres")]
        [DisplayName("Nombre")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "Contraseña es requerida")]
        [StringLength(int.MaxValue, MinimumLength = 6, ErrorMessage="Contraseña debe contener entre 6 a 20 caracteres")]
        [DisplayName("Contraseña")]
        public string clave { get; set; }
    
        public virtual ICollection<Comentario> Comentarios { get; set; }
        public virtual ICollection<Lista> Listas { get; set; }
        public virtual ICollection<Pedido> Pedidos { get; set; }
    }
}
